#! /bin/bash

################
# Configuration
################
problemId="stack"
studentCodeName="MyStack"
interfaceName="Stack"
testsName="StackProps"
forbiddenClasses=(
	"java.util.Stack"
)

feedback-msg -ae -m "test\n\n"
feedback-msh -ae "<img src=\"https://inginious.info.ucl.ac.be/static/common/images/header.png\" />"

. ./execute_implementation
execute_implementation $problemId $studentCodeName $interfaceName forbiddenClasses $testsName
