#! /bin/bash
# TODO handle compilation errors + check +/-...
getinput stack > MyStack.java

cheat=$(cat MyStack.java | grep -c "import java.util.Stack")
if [ $cheat != "0" ]; then
	feedback --result failed --feedback "You can't use java.util.Stack!"
else

	javac MyStack.java
	scalac -cp .:scalacheck.jar StackProps.scala
	output=$(scala -cp .:scalacheck.jar StackProps)
	
    failed=$(echo "$output" | grep -c "-")
    passed=$(echo "$output" | grep -c "+")

	if [ "$failed" = "0" ]; then
		feedback --result success --feedback "Congratulations, you passed all the tests!"
	else
		feedback --result failed --feedback "Unfortunately, you failed $failed tests out of $(($passed+$failed))"
	fi

fi
