#! /bin/bash
# TODO no import of java.util.Stack + handle compilation errors + check +/-...
getinput stack > MyStack.java
javac MyStack.java
scalac -cp .:scalacheck.jar StackProps.scala
output=$(scala -cp .:scalacheck.jar StackProps)
output="$output test"
#if [ "$output" = "OK" ]; then
	feedback --result success --feedback "$output" #"Toutes mes félicitations!"
#else
#	feedback --result failed --feedback "Tu as lamentablement échoué"
#fi
