#! /bin/bash
# BuggyKruskal : 
# 1 : costs of all edges are artificially incremented ==> not optimal
# 2 : LinkedList instead of PriorityQueue ==> not optimal
# 3 : too few edges (1 less) ==> not connected OR not enough nodes
# 4 : one node was removed from the graph
# 5 : disconnects the graph while keeping every other parameter identical. 

tot=6 # number of tests
name="Kruskal"
testName="KruskalTests"
word="Kruskal"
getinput archive > arch.zip
unzip arch.zip -d ./student

getinput tests > "student/$testName.java"
cp junit-4.12.jar student/junit-4.12.jar
cp hamcrest-core-1.3.jar student/hamcrest-core-1.3.jar
cp Kruskal.java student/Kruskal.java
cd student

n=0 # number of tests passed
passOk=0
failOk=0
buggyName="Buggy$name"
oldName="$name"

for i in $(seq 1 $tot)
do
	
	cp "../${name}.java" "./${oldName}.java"
	name="${buggyName}${i}"

	javac "${oldName}.java"

	# Compile the student code and parse it properly
	compilationMessage=$(javac -cp .:junit-4.12.jar "${testName}.java" 2>&1)
	compilationMessage=$(echo "$compilationMessage" | sed -e 's/^/\t/' | sed -e 's/%/%%%/g')
	compilationMessage=$(printf "Compilation of $testName.java failed :\n::\n\n $compilationMessage")
	if [ ! -f "$testName.class" ]; then
    	feedback --result failed --feedback "$compilationMessage"
    	exit 0
	fi

	output=$(run_student java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore "$testName")
    r=$?
    
	if [ "$r" = "252" ]; then
		feedback --result failed --feedback "Command was killed due to an out-of-memory"
		exit 0
	elif [ "$r" = "253" ]; then
		feedback --result timeout --feedback "Command timed out"
		exit 0
	elif [ "$r" = "254" ]; then
	      feedback --result failed --feedback "Unfortunately, a runtime error occured"
		exit 0
	fi

	failed=$(echo "$output" | grep -c "FAILURES")
    passed=$(echo "$output" | grep -c "OK")

	if [ "$i" = "1" ] && [ "$failed" = "0" ] && [ "$passed" != "0" ]; then
		((n++))
		((passOk++))
	fi

	if [ "$i" != "1" ] && [ "$failed" = "1" ] && [ "$passed" = "0" ]; then
		((n++))
		((failOk++))
	fi
done
cd ..

feedback=""
if [ "$passOk" != 1 ]; then
	feedback="you detected an error in a correct $word implementation"
fi
if [ "$failOk" != "$(($tot-1))" ]; then
	if [ "$feedback" != "" ]; then
    		feedback="$feedback and "
    	fi
    	lack=$(($tot-1-$failOk))
	feedback="you didn't detect errors in $lack incorrect ${word} implementations. "
fi

if [ "$n" = "$tot" ]; then
	feedback --result success --feedback "Congratulations, you passed the $n tests!"
else
	feedback --result failed --feedback "Unfortunately, you passed only $n tests out of $tot : $feedback"
fi
