#! /bin/bash

getinput plagiarism > student/Plagiarism.java
getinput hashmap > student/HashMap.java

cp MapInterface.java ./student
cp PlagiarismInterface.java ./student

cp MyHashMap.java student/MyHashMap.java
cp MyPlagiarism.java student/MyPlagiarism.java
cp Tester.java ./student/Tester.java
cp ./*.txt ./student/
cp -r ./corpus ./student
cp -r ./corpus2 ./student
cp -r ./corpus3 ./student
cp -r ./corpus4 ./student

cd student

# Compile the student code and parse it properly
compilationMessage=$(javac Plagiarism.java PlagiarismInterface.java HashMap.java MapInterface.java 2>&1)
compilationMessage=$(echo "$compilationMessage" | sed -e 's/^/\t/' | sed -e 's/%/%%%/g')
compilationMessage=$(printf "Compilation failed :\n::\n\n $compilationMessage")
if [ ! -f Plagiarism.class ]; then
    feedback --result failed --feedback "$compilationMessage"
    exit 0
fi


javac Tester.java
output=$(java Tester)
cd ..

if [ "$output" = "252" ]; then
	feedback --result failed --feedback "Command was killed due to an out-of-memory"
elif [ "$output" = "253" ]; then
	feedback --result failed --feedback "Command timed out"
elif [ "$output" = "254" ]; then
    feedback --result failed --feedback "Unfortunately, a runtime error occured"
else

    failed=$(echo "$output" | grep -c "failed :")
	passed=$(echo "$output" | grep -c "passed")
	problem=$(echo "$output" | grep -c "An error occured")

	if [ "$problem" != "0" ]; then
    	feedback --result failed --feedback "Unfortunately, an exception occured during the execution of your code. "
	elif [ "$passed" != "0" ] && [ "$failed" = "0" ]; then
    	FEED=$(printf "Congratulations, you passed all the tests!\n$output")
		feedback --result success --feedback "$FEED"
	elif [ "$failed" != "0" ]; then
        FEED=$(printf "Unfortunately, you failed some tests : \n$output")
        feedback --result failed --feedback "$FEED"
	else # should never happen
    	FEED=$(printf "Sorry, it seems that an error occured in the grading script, please contact the course administrator. ")
        feedback --result failed --feedback "$FEED"
	fi
fi
