#! /bin/bash

getinput file > Main.java
javac Main.java
output=$(java Main)
if [ "$output" = "Hello World!" ]; then
	feedback --result success --feedback "Toutes mes félicitations!"
else
	feedback --result failed --feedback "Tu as lamentablement échoué"
fi