#! /bin/bash

getinput file > file.java
javac file.java
output=$(java file)
if [ "$output" = "Hello World!" ]; then
	feedback --result success --feedback "Toutes mes félicitations!"
else
	feedback --result failed --feedback "Tu as lamentablement échoué"
fi
