#! /bin/bash

# This script copies all the necessary components in the right folder

implementations=(
    "m1stack"
    "preexam_bfs"
    "preexam_dfs"
    "preexam_merge_sort"
)

for folder in "${implementations[@]}"
do
    cp execute ../${folder}
    cp RunTests.java ../${folder}/student/
done

cp execute_implementation ../m1interpreter
cp execute_implementation ../m3orderedmap

tests=(
    "m1stacktests"
    "m1interpretertests"
    "m3tests"
    "m4_plagiarism_tests"
    "m5_compressor_tests"
    "m6_kruskal_tests"
)

for folder in "${tests[@]}"
do
    cp execute_test ../${folder}
done
