#! /bin/bash
getinput interpreter > student/Interpreter.java
getinput stack > student/MyStack.java
getinput element > student/Element.java

javac student/Element.java student/MyStack.java student/Interpreter.java

if [ ! -f student/MyStack.class ]; then
    feedback --result failed --feedback "Compilation of MyStack.java failed"
    exit 0
fi

if [ ! -f student/Interpreter.class ]; then
    feedback --result failed --feedback "Compilation of Interpreter.java failed"
    exit 0
fi

# Copy everything in the 'student' directory for run_student
cat InterpreterProps.scala > student/InterpreterProps.scala
cp scalacheck.jar student/scalacheck.jar
cd student
scalac -cp .:scalacheck.jar InterpreterProps.scala
output=$(run_student scala -cp .:scalacheck.jar InterpreterProps)
cd ..

if [ "$output" = "252" ]; then
	feedback --result failed --feedback "Command was killed due to an out-of-memory"
elif [ "$output" = "253" ]; then
	feedback --result failed --feedback "Command timed out"
elif [ "$output" = "254" ]; then
      feedback --result failed --feedback "An runtime error occured"
else
    failed=$(echo "$output" | grep -c "Falsified")
	passed=$(echo "$output" | grep -c "OK")

	if [ "$failed" = "0" ]; then
		feedback --result success --feedback "Congratulations, you passed all the tests!"
	else
		feedback --result failed --feedback "Unfortunately, you failed $failed tests out of $(($passed+$failed))"
	fi
fi
