#! /bin/bash

################
# Configuration
#-----------------
# 01-10-2016 : XGI : Remplacement des tests unitaires en Scala par ceux implém avec JUnit.
#                    Ajout de la classe interdite java.util.Stack
# 04-10-2016 : FKA : Modification de run et execute pour que ca utilise le script général
#                    de common/
################
names=(
    "Interpreter"
)
forbiddenClasses=(
	"java.util.Stack"
)

getinput "interpreter" > "student/Interpreter.java"

. ./execute
execute names forbiddenClasses
