#! /bin/bash

################
# Configuration
################
problemId="interpreter"
studentCodeName="Interpreter"
interfaceName="InterpreterInterface"
testsName="InterpreterProps"
forbiddenClasses=(

)

. ./execute_implementation
execute_implementation $problemId $studentCodeName $interfaceName forbiddenClasses $testsName
