#! /bin/bash

#################
# Configuration
#################
problemId="interpreter"
studentCodeName="Interpreter"
interfaceName="InterpreterInterface"
testsName="InterpreterTests"

#################
# Execution of tests
#################
getinput "${problemId}" > "student/${studentCodeName}.java"
cp junit-4.12.jar student/junit-4.12.jar
cp hamcrest-core-1.3.jar student/hamcrest-core-1.3.jar
cp "${testsName}.java" "student/${testsName}.java"
cp "${interfaceName}.java" "student/${interfaceName}.java"

# Compile the student code and parse it properly
compilationMessage=$(javac -cp .:junit-4.12.jar student/${interfaceName}.java student/${studentCodeName}.java student/${testsName}.java 2>&1)
compilationMessage=$(echo "$compilationMessage" | sed -e 's/^/\t/' | sed -e 's/%/%%%/g')
compilationMessage=$(printf "Compilation of ${studentCodeName}.java failed :\n::\n\n $compilationMessage")
if [ ! -f "student/${studentCodeName}.class" ]; then
    feedback --result failed --feedback "$compilationMessage"
    exit 0
fi

cd student

# We execute the tests
output=$(run_student java -cp .:junit-4.12.jar:hamcrest-core-1.3.jar ${testsName})
echo "${output}"
r=$?
cd ..

if [ "$r" = "252" ]; then
	feedback --result failed --feedback "Command was killed due to an out-of-memory"
elif [ "$r" = "253" ]; then
	feedback --result timeout --feedback "Command timed out"
elif [ "$r" = "254" ]; then
      feedback --result failed --feedback "Unfortunately, a runtime error occured"
elif [ "$r" = "1" ]; then
	# Some tests have failed
	feedback-result failed
	feedback-msg -ae -m "${output}"
	feedback-msg -ae -m "Unfortunately, you failed some tests"
elif [ "$r" = "0" ]; then
	# All tests passed !
	feedback --result success --feedback "Congratulations, you passed the $passed tests!"
fi