#! /bin/bash

################
# Configuration
################
problemId="ordered_map"
studentCodeName="SearchTree"
interfaceName="OrderedMap"
testsName="OrderedMapProps"
forbiddenClasses=(
	"java.util.TreeMap"
	"java.util.concurrent.ConcurrentSkipListMap"
	"Arrays.sort"
)

# Specific fo rthis tests
cp songs.txt student/songs.txt

. ./execute_implementation
execute_implementation $problemId $studentCodeName $interfaceName forbiddenClasses $testsName
