#! /bin/bash
getinput ordered_map > student/SearchTree.java
cp OrderedMap.java student/OrderedMap.java

patterns="java.util.TreeMap|java.util.concurrent.ConcurrentSkipListMap"
cheat=$(cat student/SearchTree.java | grep -c -E "$patterns")
if [ $cheat != "0" ]; then
	feedback --result failed --feedback "You can't use an exising Ordered Map implementation!"
    exit 0
fi

cheat2=$(cat student/SearchTree.java | grep -c "Arrays.sort")
if [ $cheat2 != "0" ]; then
	feedback --result failed --feedback "You can't use Arrays.sort, you must implement the QuickSort algorithm yourself!"
    exit 0
fi

# Compile the student code and parse it properly
compilationMessage=$(javac student/SearchTree.java student/OrderedMap.java 2>&1)
compilationMessage=$(echo "$compilationMessage" | sed -e 's/^/\t/' | sed -e 's/%/%%%/g')
compilationMessage=$(printf "Compilation of SearchTree.java failed :\n::\n\n $compilationMessage")
if [ ! -f student/SearchTree.class ]; then
    feedback --result failed --feedback "$compilationMessage"
    exit 0
fi

# Copy everything in the 'student' directory for run_student
cp OrderedMapProps.scala student/OrderedMapProps.scala
cp scalacheck.jar student/scalacheck.jar
cp songs.txt student/songs.txt
cd student
scalac -cp .:scalacheck.jar OrderedMapProps.scala

if [ ! -f OrderedMapProps.class ]; then
    feedback --result failed --feedback "An error occured during the compilation of the test script. Make sure your class follows the specifications. "
    exit 0
fi

output=$(run_student scala -cp .:scalacheck.jar -J-Xmx2g -J-Xms2g OrderedMapProps)
r=$?
cd ..

if [ "$r" = "252" ]; then
	feedback --result failed --feedback "Command was killed due to an out-of-memory"
elif [ "$r" = "253" ]; then
	feedback --result timeout --feedback "Command timed out"
elif [ "$r" = "254" ]; then
    feedback --result failed --feedback "Unfortunately, a runtime error occured"
else
	failed=$(echo "$output" | grep -c "Falsified")
	passed=$(echo "$output" | grep -c "OK")
	infos=$(echo "$output" | grep -o '! \w*.\w*')

	if [ "$failed" = "0" ] && [ "$passed" = "0" ]; then
    	feedback --result failed --feedback "It seems like an internal error occured. Maybe a Stack Overflow ? If this persists, please contact your course administrator. "
	elif [ "$failed" = "0" ]; then
		feedback --result success --feedback "Congratulations, you passed the $passed tests! "
	else
		feedback --result failed --feedback "Unfortunately, you failed $failed tests out of $(($passed+$failed)) : $infos"
	fi
fi