#!/bin/bash

name="BreadthFirstShortestPaths"

parsetemplate --output "${name}.java" template.java

cp "${name}.java" student/

cd

output=$(javac "${name}.java" 2&>1)
retval=$?
if [ "$retval" != "0" ]; then
    #output=$(echo "$output" | sed -e 's/^/\t/' | sed -e 's/%/%%%/g')
    feedback-msg -ae -m "Compilation of ${name} failed:\n..\n\n"
    feedback-msg -ae -m "$output"
    exit 1
fi
